### ISSUE TITLE
Switch default branch to gh-pages

### ISSUE THREAD

**Issue by davelab6** [glyphr-studio/glyphr-studio-2-ui-framework#1]
If you switch the default branch to gh-pages, we can see the pages live :) 

I did this in my fork - 

* https://davelab6.github.io/glyphr-studio-2-ui-framework/dist/openproject.htm
* https://davelab6.github.io/glyphr-studio-2-ui-framework/dist/glyphedit.htm
* https://davelab6.github.io/glyphr-studio-2-ui-framework/dist/settings.htm
* https://davelab6.github.io/glyphr-studio-2-ui-framework/dist/progress_spinner.htm

- and it only takes a minute, in 3 steps:

1. create a gh-pages branch by visiting https://github.com/glyphr-studio/glyphr-studio-2-ui-framework/ and use the branch dropdown and type in `gh-pages` and click create:

<img width="343" alt="screen shot 2016-05-16 at 13 12 26" src="https://cloud.githubusercontent.com/assets/261579/15297385/d569c838-1b67-11e6-8952-5ff6ee2ce1ca.png">

2. switch the default branch to gh-pages in https://github.com/glyphr-studio/glyphr-studio-2-ui-framework/ settings

3. delete the master branch in https://github.com/glyphr-studio/glyphr-studio-2-ui-framework/branches

**Comment by mechanicious** [comment]
Managing an additional branch is a distraction, this branch is meant for developers/contributors only, there is no need for a live preview, especially with the current preview mechanics.

**Comment by davelab6** [comment]
> there is no need for a live preview

**Comment by mechanicious** [comment]
> this repo is meant for developers/contributors only
Then you're not a developers/contributors, at least that part of you which created it :D

**Comment by mechanicious** [comment]
Aside from breaking my sentence apart, I were going to implement this long time ago, however for this the preview mechanics must change, "guessing" the `url` is unwanted, therefore the pages must be inter-linked, however, liking them directly to eachother is unwanted as it is not a part of the framework. Managing an extra `index` file liking them all together, is unwanted as well. Any other option increases in complexity which is wanted even less; especially, taking into account the fact that this repo will get out of sync with the main repo as we begin adapting it as React jsx components. 

Enabling the live preview, might confuse people with a feature which is actually not supported. Hope you understand.

**Comment by davelab6** [comment]
> might confuse people

I think the URL https://glyphr-studio.github.io/glyphr-studio-2-ui-framework/dist/openproject.htm is pretty clear its a developer resource.

**Comment by davelab6** [comment]
But this is no big deal; if you say no, its fine :)
